/**
 * `molo content sentence-requests` and `molo content culture`: loading what
 * a tutor is asked to supply (docs/EDITOR-GUIDE.md, "A tutor session").
 *
 * Both read a checked-in JSON file of English and Norwegian a model drafted,
 * and neither writes a word of isiXhosa:
 *
 *   - **sentence-requests** loads `curriculum/sentence-requests.json` as
 *     requests — rows with no content status that no learner route reads —
 *     naming the words each should be built around, resolved from the
 *     lexicon verbatim. The tutor types the isiXhosa in the dashboard. The
 *     same command then turns every answered request whose sentence has been
 *     *published* into a `draft` translate_tap in its skill, with the same
 *     distractor rule `molo content curate` uses.
 *   - **culture** loads `curriculum/culture-cards.json` as `culture_card`
 *     exercises at `ai_draft`, each with the caveat its reviewer must clear.
 *     The only isiXhosa in a card is a lexicon lemma filled into a
 *     `{placeholder}`; a card naming a word the lexicon lacks is refused.
 *
 * Dry run by default; `--live` writes. Idempotent: a request or card that is
 * already there is reported and left exactly as an editor left it.
 */

import { Command, Options } from "@effect/cli";
import {
  buildLexiconIndex,
  loadCultureCards,
  planSentenceLinks,
  loadSentenceRequests,
  renderCultureCard,
  resolveRequestWords,
  tapDistractors,
  type CultureCardSpec,
  type RenderedCard,
  type RequestLexeme,
  type ResolvedWords,
  type SentenceRequestSpec,
} from "@molo/content";
import type { Actor } from "@molo/core";
import {
  actorForRef,
  coursesRepo,
  curationLexicon,
  editorRepo,
  tutorRepo,
  type Db,
} from "@molo/db";
import { Effect, Option } from "effect";

import { fail, gate, kv, out, table, withDb } from "../context.ts";
import { molo } from "../root.ts";

const asActor = Options.text("as").pipe(
  Options.withDefault("dev_editor"),
  Options.withDescription("Editor email or user id; every row is attributed to them"),
);
const unitOption = Options.text("unit").pipe(
  Options.optional,
  Options.withDescription("Only one unit, by slug (start with greet-and-introduce)"),
);

async function editorActor(db: Db, as: string): Promise<Actor | string> {
  const actor = await actorForRef(db, as);
  if (!actor) return `no user matches ${as} (pass an email or a user id)`;
  if (!actor.roles.some((r) => r === "editor" || r === "admin"))
    return `user ${as} has no editorial role`;
  return actor;
}

async function lexiconFor(db: Db): Promise<RequestLexeme[]> {
  const course = await coursesRepo(db).defaultCourse();
  const rows = await curationLexicon(db, course?.targetLang ?? "xh");
  return rows.map((r) => ({ id: r.id, lemma: r.lemma, pos: r.pos }));
}

// ---------------------------------------------------------------------------
// molo content sentence-requests
// ---------------------------------------------------------------------------

interface RequestPlan {
  readonly spec: SentenceRequestSpec;
  readonly skillId: string | null;
  readonly exists: boolean;
  readonly words: ResolvedWords;
}

const TAP_NOTE =
  "Generated by `molo content sentence-requests` from a tutor's sentence. Draft: an editor checks the tiles and the distractors.";

export const sentenceRequests = Command.make(
  "sentence-requests",
  { as: asActor, unit: unitOption },
  ({ as, unit }) =>
    Effect.gen(function* () {
      const g = yield* molo;
      const unitSlug = Option.getOrUndefined(unit);
      const file = loadSentenceRequests();
      const specs = file.requests.filter((r) => !unitSlug || r.unitSlug === unitSlug);
      if (specs.length === 0 && unitSlug)
        return yield* fail(`curriculum/sentence-requests.json has no requests for ${unitSlug}`);

      yield* withDb(g, (db) =>
        Effect.gen(function* () {
          const actor = yield* Effect.promise(() => editorActor(db, as));
          if (typeof actor === "string") return yield* fail(actor);
          const repo = tutorRepo(db, actor);
          const course = yield* Effect.promise(() => coursesRepo(db).defaultCourse());
          const skills = yield* Effect.promise(() => repo.skillsByKey(course?.id));
          const words = yield* Effect.promise(() =>
            repo.skillWords([...skills.values()].map((s) => s.id)),
          );
          const lexicon = yield* Effect.promise(() => lexiconFor(db));

          const plan: RequestPlan[] = [];
          for (const spec of specs) {
            const skill = skills.get(`${spec.unitSlug}/${spec.skillSlug}`);
            const taught = new Set(skill ? (words.get(skill.id) ?? []) : []);
            plan.push({
              spec,
              skillId: skill?.id ?? null,
              exists: skill
                ? (yield* Effect.promise(() => repo.findRequest(skill.id, spec.slug))) !== null
                : false,
              words: resolveRequestWords(spec.words, lexicon, taught),
            });
          }

          // Answered requests whose sentence an editor has published: those
          // become translate_tap drafts in their skill.
          const candidates = yield* Effect.promise(() => repo.tapCandidates(unitSlug));
          const taps = candidates.map((c) => ({
            ...c,
            state:
              c.existingExerciseId !== null
                ? "already there"
                : c.sentenceStatus !== "published"
                  ? `sentence is ${c.sentenceStatus}`
                  : c.tokenLexemeIds.length === 0
                    ? "sentence has no tokens"
                    : "would write",
          }));

          yield* out(
            g,
            {
              requests: plan.map((p) => ({
                request: `${p.spec.unitSlug}/${p.spec.skillSlug}/${p.spec.slug}`,
                en: p.spec.en,
                state: stateOf(p),
                words: p.words.lexemeIds.length,
                outsideSkill: p.words.outsideSkill,
                rejected: p.words.rejected,
              })),
              translateTaps: taps.map((t) => ({
                request: `${t.unitSlug}/${t.skillSlug}/${t.requestSlug}`,
                sentenceId: t.sentenceId,
                state: t.state,
              })),
            },
            () => renderRequests(plan, taps),
          );

          const toWrite = plan.filter((p) => p.skillId !== null && !p.exists);
          const tapsToWrite = taps.filter((t) => t.state === "would write");
          if (toWrite.length === 0 && tapsToWrite.length === 0) {
            if (g.json !== true) console.log("\nnothing to write.");
            return;
          }
          const apply = yield* gate(
            g,
            `write ${toWrite.length} sentence requests (editor-only; no learner reads them) ` +
              `and ${tapsToWrite.length} translate_tap exercises as draft`,
          );
          if (!apply) return;

          const written: Array<{ request: string; id: string }> = [];
          for (const p of toWrite) {
            const id = yield* Effect.promise(() =>
              repo.createRequest({
                skillId: p.skillId as string,
                slug: p.spec.slug,
                order: p.spec.order,
                promptEn: p.spec.en,
                promptNb: p.spec.nb,
                note: p.spec.note ?? null,
                targetLexemeIds: p.words.lexemeIds,
              }),
            );
            written.push({ request: `${p.spec.unitSlug}/${p.spec.skillSlug}/${p.spec.slug}`, id });
          }
          const tapsWritten: Array<{ request: string; exercise: string }> = [];
          for (const t of tapsToWrite) {
            const id = yield* Effect.promise(() =>
              repo.addTranslateTap({
                skillId: t.skillId,
                sentenceId: t.sentenceId,
                distractorLexemeIds: tapDistractors(words.get(t.skillId) ?? [], t.tokenLexemeIds),
                note: `${TAP_NOTE} (request ${t.requestSlug})`,
              }),
            );
            tapsWritten.push({
              request: `${t.unitSlug}/${t.skillSlug}/${t.requestSlug}`,
              exercise: id,
            });
          }
          yield* out(g, { written, tapsWritten }, () => {
            console.log("\nrequests written (open, waiting for the tutor in /edit/write):");
            table(written);
            if (tapsWritten.length > 0) {
              console.log("\ntranslate_tap exercises written as draft:");
              table(tapsWritten);
            }
          });
        }),
      );
    }),
).pipe(
  Command.withDescription(
    "Load curriculum/sentence-requests.json for the tutor, and build translate_tap drafts from published answers (--live writes)",
  ),
);

function stateOf(p: RequestPlan): string {
  if (p.skillId === null) return "no such skill";
  return p.exists ? "already there" : "would write";
}

function renderRequests(
  plan: readonly RequestPlan[],
  taps: ReadonlyArray<{ unitSlug: string; skillSlug: string; requestSlug: string; state: string }>,
): void {
  console.log(
    "sentence requests (English and Norwegian only; the tutor writes the isiXhosa in /edit/write)\n",
  );
  table(
    plan.map((p) => ({
      skill: `${p.spec.unitSlug}/${p.spec.skillSlug}`,
      request: p.spec.slug,
      state: stateOf(p),
      words: p.words.lexemeIds.length,
      dropped: p.words.rejected.map((r) => `${r.word} (${r.reason})`).join(", "),
    })),
  );
  const outside = plan.filter((p) => p.words.outsideSkill.length > 0);
  if (outside.length > 0) {
    console.log(
      "\nwords found in the lexicon but not taught by the request's skill (fine, worth a look):",
    );
    table(outside.map((p) => ({ request: p.spec.slug, words: p.words.outsideSkill.join(", ") })));
  }
  console.log("\nanswered requests -> translate_tap");
  table(
    taps.map((t) => ({ request: `${t.unitSlug}/${t.skillSlug}/${t.requestSlug}`, state: t.state })),
  );
}

// ---------------------------------------------------------------------------
// molo content culture
// ---------------------------------------------------------------------------

interface CardPlan {
  readonly spec: CultureCardSpec;
  readonly skillId: string | null;
  readonly existingId: string | null;
  readonly rendered: RenderedCard | null;
  readonly missing: readonly string[];
}

export const culture = Command.make("culture", { as: asActor, unit: unitOption }, ({ as, unit }) =>
  Effect.gen(function* () {
    const g = yield* molo;
    const unitSlug = Option.getOrUndefined(unit);
    const file = loadCultureCards();
    const specs = file.cards.filter((c) => !unitSlug || c.unitSlug === unitSlug);
    if (specs.length === 0 && unitSlug)
      return yield* fail(`curriculum/culture-cards.json has no cards for ${unitSlug}`);

    yield* withDb(g, (db) =>
      Effect.gen(function* () {
        const actor = yield* Effect.promise(() => editorActor(db, as));
        if (typeof actor === "string") return yield* fail(actor);
        const repo = tutorRepo(db, actor);
        const course = yield* Effect.promise(() => coursesRepo(db).defaultCourse());
        const skills = yield* Effect.promise(() => repo.skillsByKey(course?.id));
        const lexicon = yield* Effect.promise(() => lexiconFor(db));

        const plan: CardPlan[] = [];
        for (const spec of specs) {
          const skill = skills.get(`${spec.unitSlug}/${spec.skillSlug}`);
          const result = renderCultureCard(spec, lexicon);
          plan.push({
            spec,
            skillId: skill?.id ?? null,
            existingId: skill
              ? ((yield* Effect.promise(() =>
                  repo.findCultureCard(skill.id, spec.slug, spec.title.en),
                ))?.id ?? null)
              : null,
            rendered: result.ok ? result.card : null,
            missing: result.ok ? [] : result.missing,
          });
        }

        yield* out(
          g,
          {
            cards: plan.map((p) => ({
              card: p.spec.slug,
              skill: `${p.spec.unitSlug}/${p.spec.skillSlug}`,
              state: cardState(p),
              missingWords: p.missing,
              strayWords: p.rendered?.strayWords ?? [],
            })),
          },
          () => renderCards(plan),
        );

        const toWrite = plan.filter((p) => cardState(p) === "would write");
        if (toWrite.length === 0) {
          if (g.json !== true) console.log("\nnothing to write.");
          return;
        }
        const apply = yield* gate(
          g,
          `write ${toWrite.length} culture cards as ai_draft ` +
            `(nothing is published; each waits for the tutor to confirm its caveat)`,
        );
        if (!apply) return;

        const written: Array<{ card: string; id: string }> = [];
        for (const p of toWrite) {
          const id = yield* Effect.promise(() =>
            repo.addCultureCard({
              skillId: p.skillId as string,
              slug: p.spec.slug,
              payload: (p.rendered as RenderedCard).payload,
              caveat: p.spec.caveat,
            }),
          );
          written.push({ card: p.spec.slug, id });
        }
        yield* out(g, { written }, () => {
          console.log("\nwritten as ai_draft:");
          table(written);
          console.log(
            "\nNothing here is published. Each card waits in /edit/culture with its caveat:\n" +
              "the claims the tutor confirms or strikes before a second editor can approve it.",
          );
        });
      }),
    );
  }),
).pipe(
  Command.withDescription(
    "Load curriculum/culture-cards.json as ai_draft culture cards for the tutor to check (--live writes)",
  ),
);

function cardState(p: CardPlan): string {
  if (p.skillId === null) return "no such skill";
  if (p.missing.length > 0) return "refused: word not in lexicon";
  if (p.existingId !== null) return "already there";
  return "would write";
}

function renderCards(plan: readonly CardPlan[]): void {
  console.log(
    "culture cards (nothing here is published; every card enters as ai_draft with its caveat)\n",
  );
  table(
    plan.map((p) => ({
      card: p.spec.slug,
      skill: `${p.spec.unitSlug}/${p.spec.skillSlug}`,
      state: cardState(p),
      words: p.spec.words.length,
      claims: p.spec.caveat.split("\n").length,
    })),
  );
  const refused = plan.filter((p) => p.missing.length > 0);
  if (refused.length > 0) {
    console.log("\nrefused rather than guessed: these words are not in the lexicon");
    kv(Object.fromEntries(refused.map((p) => [p.spec.slug, p.missing.join(", ")])));
  }
  const stray = plan.filter((p) => (p.rendered?.strayWords.length ?? 0) > 0);
  if (stray.length > 0) {
    console.log(
      "\nlexicon words in the prose outside a {placeholder} (check each is really English or Norwegian):",
    );
    table(
      stray.flatMap((p) =>
        (p.rendered as RenderedCard).strayWords.map((s) => ({
          card: p.spec.slug,
          lang: s.lang,
          word: s.word,
        })),
      ),
    );
  }
}

/**
 * `molo content link-sentences`: link the words of the tutors' sentences to
 * the lexicon, as far as that needs no judgement (@molo/content
 * sentence-links). A word is linked only when its written form is a lemma or
 * an infinitive; a lemma is xh-morph-verified, an infinitive is not. The rest
 * is printed for an editor, with the request's words that appear inside an
 * unlinked word as hints. Only sentences with no links at all are touched, so
 * an editor's work is never overwritten; nothing is published.
 */
export const linkSentences = Command.make(
  "link-sentences",
  { as: asActor, unit: unitOption },
  ({ as, unit }) =>
    Effect.gen(function* () {
      const g = yield* molo;
      const unitSlug = Option.getOrUndefined(unit);
      yield* withDb(g, (db) =>
        Effect.gen(function* () {
          const actor = yield* Effect.promise(() => editorActor(db, as));
          if (typeof actor === "string") return yield* fail(actor);
          const sentences = yield* Effect.promise(() =>
            tutorRepo(db, actor).sentencesToLink(unitSlug),
          );
          const lexicon = yield* Effect.promise(() =>
            curationLexicon(db, "xh", { excludeRetired: true }),
          );
          const index = buildLexiconIndex(lexicon);
          const plans = sentences.map((s) => ({
            s,
            plan: planSentenceLinks(s.textXh, index, s.targetLexemeIds),
          }));

          yield* out(
            g,
            {
              sentences: plans.map(({ s, plan }) => ({
                sentenceId: s.sentenceId,
                skill: `${s.unitSlug}/${s.skillSlug}`,
                text: s.textXh,
                linked: plan.tokens.map((t) => ({ word: t.surfaceForm, verified: t.isLemma })),
                ambiguous: plan.ambiguous.map((a) => a.word),
                unlinked: plan.unlinked,
                requestedButUnused: plan.targetsUnused,
              })),
            },
            () => {
              if (plans.length === 0) {
                console.log("No tutor sentence is waiting for its words to be linked.");
                return;
              }
              for (const { s, plan } of plans) {
                console.log(`\n${s.unitSlug}/${s.skillSlug} · ${s.status}\n  ${s.textXh}`);
                const linked = plan.tokens.map(
                  (t) => `${t.surfaceForm}${t.isLemma ? " ✓" : " (infinitive)"}`,
                );
                if (linked.length > 0) console.log(`  link:      ${linked.join(", ")}`);
                if (plan.ambiguous.length > 0)
                  console.log(`  ambiguous: ${plan.ambiguous.map((a) => a.word).join(", ")}`);
                for (const u of plan.unlinked)
                  console.log(
                    `  for an editor: ${u.word}${u.hints.length > 0 ? `  (contains ${u.hints.join(", ")}?)` : ""}`,
                  );
              }
            },
          );

          const toWrite = plans.filter(({ plan }) => plan.tokens.length > 0);
          if (toWrite.length === 0) return;
          const apply = yield* gate(
            g,
            `link ${toWrite.reduce((n, p) => n + p.plan.tokens.length, 0)} words in ${toWrite.length} sentences ` +
              "(exact lemma or infinitive only; nothing is published, unlinked words stay for an editor)",
          );
          if (!apply) return;
          const repo = editorRepo(db, actor);
          for (const { s, plan } of toWrite) {
            yield* Effect.promise(() =>
              repo.setSentenceTokens(
                s.sentenceId,
                plan.tokens.map((t) => ({
                  position: t.position,
                  lexemeId: t.lexemeId,
                  surfaceForm: t.surfaceForm,
                  // The one case verify.ts calls verified without generating anything.
                  morphVerified: t.isLemma,
                  irregular: false,
                  irregularNote: null,
                })),
              ),
            );
          }
          if (g.json !== true)
            console.log(
              `\nlinked ${toWrite.length} sentences. Open each in /edit/sentences to finish the rest.`,
            );
        }),
      );
    }),
).pipe(
  Command.withDescription(
    "Link the words of tutor sentences to the lexicon where the form is a lemma or infinitive; the rest is listed for an editor (--live writes)",
  ),
);
