/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as DevRouteImport } from './routes/dev'
import { Route as EditRouteImport } from './routes/edit'
import { Route as GrammarRouteImport } from './routes/grammar'
import { Route as LeaguesRouteImport } from './routes/leagues'
import { Route as LexiconRouteImport } from './routes/lexicon'
import { Route as LicencesRouteImport } from './routes/licences'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as PlusRouteImport } from './routes/plus'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WithdrawalFormRouteImport } from './routes/withdrawal-form'
import { Route as DevIndexRouteImport } from './routes/dev.index'
import { Route as DevKnobsRouteImport } from './routes/dev.knobs'
import { Route as DevMascotsRouteImport } from './routes/dev.mascots'
import { Route as DevPlaygroundRouteImport } from './routes/dev.playground'
import { Route as EditIndexRouteImport } from './routes/edit.index'
import { Route as EditContentRouteImport } from './routes/edit.content'
import { Route as EditCultureRouteImport } from './routes/edit.culture'
import { Route as EditCurriculumRouteImport } from './routes/edit.curriculum'
import { Route as EditGoldensRouteImport } from './routes/edit.goldens'
import { Route as EditGrammarRouteImport } from './routes/edit.grammar'
import { Route as EditRecorderRouteImport } from './routes/edit.recorder'
import { Route as EditReviewRouteImport } from './routes/edit.review'
import { Route as EditStudioRouteImport } from './routes/edit.studio'
import { Route as EditWriteRouteImport } from './routes/edit.write'
import { Route as LegalCompanyRouteImport } from './routes/legal.company'
import { Route as PrivacyProvidersRouteImport } from './routes/privacy_.providers'
import { Route as DevDemoIdRouteImport } from './routes/dev.demo.$id'
import { Route as EditExercisesIdRouteImport } from './routes/edit.exercises.$id'
import { Route as EditExercisesNewRouteImport } from './routes/edit.exercises.new'
import { Route as EditLexemesIdRouteImport } from './routes/edit.lexemes.$id'
import { Route as EditSentencesIndexRouteImport } from './routes/edit.sentences.index'
import { Route as EditSentencesIdRouteImport } from './routes/edit.sentences.$id'
import { Route as LearnSlugIndexRouteImport } from './routes/learn.$slug.index'
import { Route as LearnSlugLessonIdRouteImport } from './routes/learn.$slug.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const EditRoute = EditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarRoute = GrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesRoute = LeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => rootRouteImport,
} as any)
const LexiconRoute = LexiconRouteImport.update({
  id: '/lexicon',
  path: '/lexicon',
  getParentRoute: () => rootRouteImport,
} as any)
const LicencesRoute = LicencesRouteImport.update({
  id: '/licences',
  path: '/licences',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlusRoute = PlusRouteImport.update({
  id: '/plus',
  path: '/plus',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawalFormRoute = WithdrawalFormRouteImport.update({
  id: '/withdrawal-form',
  path: '/withdrawal-form',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevRoute,
} as any)
const DevKnobsRoute = DevKnobsRouteImport.update({
  id: '/knobs',
  path: '/knobs',
  getParentRoute: () => DevRoute,
} as any)
const DevMascotsRoute = DevMascotsRouteImport.update({
  id: '/mascots',
  path: '/mascots',
  getParentRoute: () => DevRoute,
} as any)
const DevPlaygroundRoute = DevPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => DevRoute,
} as any)
const EditIndexRoute = EditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EditRoute,
} as any)
const EditContentRoute = EditContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => EditRoute,
} as any)
const EditCultureRoute = EditCultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => EditRoute,
} as any)
const EditCurriculumRoute = EditCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => EditRoute,
} as any)
const EditGoldensRoute = EditGoldensRouteImport.update({
  id: '/goldens',
  path: '/goldens',
  getParentRoute: () => EditRoute,
} as any)
const EditGrammarRoute = EditGrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => EditRoute,
} as any)
const EditRecorderRoute = EditRecorderRouteImport.update({
  id: '/recorder',
  path: '/recorder',
  getParentRoute: () => EditRoute,
} as any)
const EditReviewRoute = EditReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => EditRoute,
} as any)
const EditStudioRoute = EditStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => EditRoute,
} as any)
const EditWriteRoute = EditWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => EditRoute,
} as any)
const LegalCompanyRoute = LegalCompanyRouteImport.update({
  id: '/legal/company',
  path: '/legal/company',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyProvidersRoute = PrivacyProvidersRouteImport.update({
  id: '/privacy_/providers',
  path: '/privacy/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDemoIdRoute = DevDemoIdRouteImport.update({
  id: '/demo/$id',
  path: '/demo/$id',
  getParentRoute: () => DevRoute,
} as any)
const EditExercisesIdRoute = EditExercisesIdRouteImport.update({
  id: '/exercises/$id',
  path: '/exercises/$id',
  getParentRoute: () => EditRoute,
} as any)
const EditExercisesNewRoute = EditExercisesNewRouteImport.update({
  id: '/exercises/new',
  path: '/exercises/new',
  getParentRoute: () => EditRoute,
} as any)
const EditLexemesIdRoute = EditLexemesIdRouteImport.update({
  id: '/lexemes/$id',
  path: '/lexemes/$id',
  getParentRoute: () => EditRoute,
} as any)
const EditSentencesIndexRoute = EditSentencesIndexRouteImport.update({
  id: '/sentences/',
  path: '/sentences/',
  getParentRoute: () => EditRoute,
} as any)
const EditSentencesIdRoute = EditSentencesIdRouteImport.update({
  id: '/sentences/$id',
  path: '/sentences/$id',
  getParentRoute: () => EditRoute,
} as any)
const LearnSlugIndexRoute = LearnSlugIndexRouteImport.update({
  id: '/learn/$slug/',
  path: '/learn/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugLessonIdRoute = LearnSlugLessonIdRouteImport.update({
  id: '/learn/$slug/$lessonId',
  path: '/learn/$slug/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/delete-account': typeof DeleteAccountRoute
  '/dev': typeof DevRouteWithChildren
  '/edit': typeof EditRouteWithChildren
  '/grammar': typeof GrammarRoute
  '/leagues': typeof LeaguesRoute
  '/lexicon': typeof LexiconRoute
  '/licences': typeof LicencesRoute
  '/mistakes': typeof MistakesRoute
  '/plus': typeof PlusRoute
  '/preview': typeof PreviewRoute
  '/privacy': typeof PrivacyRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/withdrawal-form': typeof WithdrawalFormRoute
  '/dev/knobs': typeof DevKnobsRoute
  '/dev/mascots': typeof DevMascotsRoute
  '/dev/playground': typeof DevPlaygroundRoute
  '/edit/content': typeof EditContentRoute
  '/edit/culture': typeof EditCultureRoute
  '/edit/curriculum': typeof EditCurriculumRoute
  '/edit/goldens': typeof EditGoldensRoute
  '/edit/grammar': typeof EditGrammarRoute
  '/edit/recorder': typeof EditRecorderRoute
  '/edit/review': typeof EditReviewRoute
  '/edit/studio': typeof EditStudioRoute
  '/edit/write': typeof EditWriteRoute
  '/legal/company': typeof LegalCompanyRoute
  '/privacy/providers': typeof PrivacyProvidersRoute
  '/dev/': typeof DevIndexRoute
  '/edit/': typeof EditIndexRoute
  '/dev/demo/$id': typeof DevDemoIdRoute
  '/edit/exercises/$id': typeof EditExercisesIdRoute
  '/edit/exercises/new': typeof EditExercisesNewRoute
  '/edit/lexemes/$id': typeof EditLexemesIdRoute
  '/edit/sentences/$id': typeof EditSentencesIdRoute
  '/learn/$slug/$lessonId': typeof LearnSlugLessonIdRoute
  '/edit/sentences/': typeof EditSentencesIndexRoute
  '/learn/$slug/': typeof LearnSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/delete-account': typeof DeleteAccountRoute
  '/grammar': typeof GrammarRoute
  '/leagues': typeof LeaguesRoute
  '/lexicon': typeof LexiconRoute
  '/licences': typeof LicencesRoute
  '/mistakes': typeof MistakesRoute
  '/plus': typeof PlusRoute
  '/preview': typeof PreviewRoute
  '/privacy': typeof PrivacyRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/withdrawal-form': typeof WithdrawalFormRoute
  '/dev/knobs': typeof DevKnobsRoute
  '/dev/mascots': typeof DevMascotsRoute
  '/dev/playground': typeof DevPlaygroundRoute
  '/edit/content': typeof EditContentRoute
  '/edit/culture': typeof EditCultureRoute
  '/edit/curriculum': typeof EditCurriculumRoute
  '/edit/goldens': typeof EditGoldensRoute
  '/edit/grammar': typeof EditGrammarRoute
  '/edit/recorder': typeof EditRecorderRoute
  '/edit/review': typeof EditReviewRoute
  '/edit/studio': typeof EditStudioRoute
  '/edit/write': typeof EditWriteRoute
  '/legal/company': typeof LegalCompanyRoute
  '/privacy/providers': typeof PrivacyProvidersRoute
  '/dev': typeof DevIndexRoute
  '/edit': typeof EditIndexRoute
  '/dev/demo/$id': typeof DevDemoIdRoute
  '/edit/exercises/$id': typeof EditExercisesIdRoute
  '/edit/exercises/new': typeof EditExercisesNewRoute
  '/edit/lexemes/$id': typeof EditLexemesIdRoute
  '/edit/sentences/$id': typeof EditSentencesIdRoute
  '/learn/$slug/$lessonId': typeof LearnSlugLessonIdRoute
  '/edit/sentences': typeof EditSentencesIndexRoute
  '/learn/$slug': typeof LearnSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/delete-account': typeof DeleteAccountRoute
  '/dev': typeof DevRouteWithChildren
  '/edit': typeof EditRouteWithChildren
  '/grammar': typeof GrammarRoute
  '/leagues': typeof LeaguesRoute
  '/lexicon': typeof LexiconRoute
  '/licences': typeof LicencesRoute
  '/mistakes': typeof MistakesRoute
  '/plus': typeof PlusRoute
  '/preview': typeof PreviewRoute
  '/privacy': typeof PrivacyRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/withdrawal-form': typeof WithdrawalFormRoute
  '/dev/knobs': typeof DevKnobsRoute
  '/dev/mascots': typeof DevMascotsRoute
  '/dev/playground': typeof DevPlaygroundRoute
  '/edit/content': typeof EditContentRoute
  '/edit/culture': typeof EditCultureRoute
  '/edit/curriculum': typeof EditCurriculumRoute
  '/edit/goldens': typeof EditGoldensRoute
  '/edit/grammar': typeof EditGrammarRoute
  '/edit/recorder': typeof EditRecorderRoute
  '/edit/review': typeof EditReviewRoute
  '/edit/studio': typeof EditStudioRoute
  '/edit/write': typeof EditWriteRoute
  '/legal/company': typeof LegalCompanyRoute
  '/privacy_/providers': typeof PrivacyProvidersRoute
  '/dev/': typeof DevIndexRoute
  '/edit/': typeof EditIndexRoute
  '/dev/demo/$id': typeof DevDemoIdRoute
  '/edit/exercises/$id': typeof EditExercisesIdRoute
  '/edit/exercises/new': typeof EditExercisesNewRoute
  '/edit/lexemes/$id': typeof EditLexemesIdRoute
  '/edit/sentences/$id': typeof EditSentencesIdRoute
  '/learn/$slug/$lessonId': typeof LearnSlugLessonIdRoute
  '/edit/sentences/': typeof EditSentencesIndexRoute
  '/learn/$slug/': typeof LearnSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/delete-account'
    | '/dev'
    | '/edit'
    | '/grammar'
    | '/leagues'
    | '/lexicon'
    | '/licences'
    | '/mistakes'
    | '/plus'
    | '/preview'
    | '/privacy'
    | '/review'
    | '/settings'
    | '/terms'
    | '/welcome'
    | '/withdrawal-form'
    | '/dev/knobs'
    | '/dev/mascots'
    | '/dev/playground'
    | '/edit/content'
    | '/edit/culture'
    | '/edit/curriculum'
    | '/edit/goldens'
    | '/edit/grammar'
    | '/edit/recorder'
    | '/edit/review'
    | '/edit/studio'
    | '/edit/write'
    | '/legal/company'
    | '/privacy/providers'
    | '/dev/'
    | '/edit/'
    | '/dev/demo/$id'
    | '/edit/exercises/$id'
    | '/edit/exercises/new'
    | '/edit/lexemes/$id'
    | '/edit/sentences/$id'
    | '/learn/$slug/$lessonId'
    | '/edit/sentences/'
    | '/learn/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/delete-account'
    | '/grammar'
    | '/leagues'
    | '/lexicon'
    | '/licences'
    | '/mistakes'
    | '/plus'
    | '/preview'
    | '/privacy'
    | '/review'
    | '/settings'
    | '/terms'
    | '/welcome'
    | '/withdrawal-form'
    | '/dev/knobs'
    | '/dev/mascots'
    | '/dev/playground'
    | '/edit/content'
    | '/edit/culture'
    | '/edit/curriculum'
    | '/edit/goldens'
    | '/edit/grammar'
    | '/edit/recorder'
    | '/edit/review'
    | '/edit/studio'
    | '/edit/write'
    | '/legal/company'
    | '/privacy/providers'
    | '/dev'
    | '/edit'
    | '/dev/demo/$id'
    | '/edit/exercises/$id'
    | '/edit/exercises/new'
    | '/edit/lexemes/$id'
    | '/edit/sentences/$id'
    | '/learn/$slug/$lessonId'
    | '/edit/sentences'
    | '/learn/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/delete-account'
    | '/dev'
    | '/edit'
    | '/grammar'
    | '/leagues'
    | '/lexicon'
    | '/licences'
    | '/mistakes'
    | '/plus'
    | '/preview'
    | '/privacy'
    | '/review'
    | '/settings'
    | '/terms'
    | '/welcome'
    | '/withdrawal-form'
    | '/dev/knobs'
    | '/dev/mascots'
    | '/dev/playground'
    | '/edit/content'
    | '/edit/culture'
    | '/edit/curriculum'
    | '/edit/goldens'
    | '/edit/grammar'
    | '/edit/recorder'
    | '/edit/review'
    | '/edit/studio'
    | '/edit/write'
    | '/legal/company'
    | '/privacy_/providers'
    | '/dev/'
    | '/edit/'
    | '/dev/demo/$id'
    | '/edit/exercises/$id'
    | '/edit/exercises/new'
    | '/edit/lexemes/$id'
    | '/edit/sentences/$id'
    | '/learn/$slug/$lessonId'
    | '/edit/sentences/'
    | '/learn/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  DevRoute: typeof DevRouteWithChildren
  EditRoute: typeof EditRouteWithChildren
  GrammarRoute: typeof GrammarRoute
  LeaguesRoute: typeof LeaguesRoute
  LexiconRoute: typeof LexiconRoute
  LicencesRoute: typeof LicencesRoute
  MistakesRoute: typeof MistakesRoute
  PlusRoute: typeof PlusRoute
  PreviewRoute: typeof PreviewRoute
  PrivacyRoute: typeof PrivacyRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  WelcomeRoute: typeof WelcomeRoute
  WithdrawalFormRoute: typeof WithdrawalFormRoute
  LegalCompanyRoute: typeof LegalCompanyRoute
  PrivacyProvidersRoute: typeof PrivacyProvidersRoute
  LearnSlugLessonIdRoute: typeof LearnSlugLessonIdRoute
  LearnSlugIndexRoute: typeof LearnSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar': {
      id: '/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof GrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues': {
      id: '/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof LeaguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lexicon': {
      id: '/lexicon'
      path: '/lexicon'
      fullPath: '/lexicon'
      preLoaderRoute: typeof LexiconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licences': {
      id: '/licences'
      path: '/licences'
      fullPath: '/licences'
      preLoaderRoute: typeof LicencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plus': {
      id: '/plus'
      path: '/plus'
      fullPath: '/plus'
      preLoaderRoute: typeof PlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdrawal-form': {
      id: '/withdrawal-form'
      path: '/withdrawal-form'
      fullPath: '/withdrawal-form'
      preLoaderRoute: typeof WithdrawalFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/knobs': {
      id: '/dev/knobs'
      path: '/knobs'
      fullPath: '/dev/knobs'
      preLoaderRoute: typeof DevKnobsRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/mascots': {
      id: '/dev/mascots'
      path: '/mascots'
      fullPath: '/dev/mascots'
      preLoaderRoute: typeof DevMascotsRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/playground': {
      id: '/dev/playground'
      path: '/playground'
      fullPath: '/dev/playground'
      preLoaderRoute: typeof DevPlaygroundRouteImport
      parentRoute: typeof DevRoute
    }
    '/edit/': {
      id: '/edit/'
      path: '/'
      fullPath: '/edit/'
      preLoaderRoute: typeof EditIndexRouteImport
      parentRoute: typeof EditRoute
    }
    '/edit/content': {
      id: '/edit/content'
      path: '/content'
      fullPath: '/edit/content'
      preLoaderRoute: typeof EditContentRouteImport
      parentRoute: typeof EditRoute
    }
    '/edit/culture': {
      id: '/edit/culture'
      path: '/culture'
      fullPath: '/edit/culture'
      preLoaderRoute: typeof EditCultureRouteImport
      parentRoute: typeof EditRoute
    }
    '/edit/curriculum': {
      id: '/edit/curriculum'
      path: '/curriculum'
      fullPath: '/edit/curriculum'
      preLoaderRoute: typeof EditCurriculumRouteImport
      parentRoute: typeof EditRoute
    }
    '/edit/goldens': {
      id: '/edit/goldens'
      path: '/goldens'
      fullPath: '/edit/goldens'
      preLoaderRoute: typeof EditGoldensRouteImport
      parentRoute: typeof EditRoute
    }
    '/edit/grammar': {
      id: '/edit/grammar'
      path: '/grammar'
      fullPath: '/edit/grammar'
      preLoaderRoute: typeof EditGrammarRouteImport
      parentRoute: typeof EditRoute
    }
    '/edit/recorder': {
      id: '/edit/recorder'
      path: '/recorder'
      fullPath: '/edit/recorder'
      preLoaderRoute: typeof EditRecorderRouteImport
      parentRoute: typeof EditRoute
    }
    '/edit/review': {
      id: '/edit/review'
      path: '/review'
      fullPath: '/edit/review'
      preLoaderRoute: typeof EditReviewRouteImport
      parentRoute: typeof EditRoute
    }
    '/edit/studio': {
      id: '/edit/studio'
      path: '/studio'
      fullPath: '/edit/studio'
      preLoaderRoute: typeof EditStudioRouteImport
      parentRoute: typeof EditRoute
    }
    '/edit/write': {
      id: '/edit/write'
      path: '/write'
      fullPath: '/edit/write'
      preLoaderRoute: typeof EditWriteRouteImport
      parentRoute: typeof EditRoute
    }
    '/legal/company': {
      id: '/legal/company'
      path: '/legal/company'
      fullPath: '/legal/company'
      preLoaderRoute: typeof LegalCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy_/providers': {
      id: '/privacy_/providers'
      path: '/privacy/providers'
      fullPath: '/privacy/providers'
      preLoaderRoute: typeof PrivacyProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/demo/$id': {
      id: '/dev/demo/$id'
      path: '/demo/$id'
      fullPath: '/dev/demo/$id'
      preLoaderRoute: typeof DevDemoIdRouteImport
      parentRoute: typeof DevRoute
    }
    '/edit/exercises/$id': {
      id: '/edit/exercises/$id'
      path: '/exercises/$id'
      fullPath: '/edit/exercises/$id'
      preLoaderRoute: typeof EditExercisesIdRouteImport
      parentRoute: typeof EditRoute
    }
    '/edit/exercises/new': {
      id: '/edit/exercises/new'
      path: '/exercises/new'
      fullPath: '/edit/exercises/new'
      preLoaderRoute: typeof EditExercisesNewRouteImport
      parentRoute: typeof EditRoute
    }
    '/edit/lexemes/$id': {
      id: '/edit/lexemes/$id'
      path: '/lexemes/$id'
      fullPath: '/edit/lexemes/$id'
      preLoaderRoute: typeof EditLexemesIdRouteImport
      parentRoute: typeof EditRoute
    }
    '/edit/sentences/': {
      id: '/edit/sentences/'
      path: '/sentences'
      fullPath: '/edit/sentences/'
      preLoaderRoute: typeof EditSentencesIndexRouteImport
      parentRoute: typeof EditRoute
    }
    '/edit/sentences/$id': {
      id: '/edit/sentences/$id'
      path: '/sentences/$id'
      fullPath: '/edit/sentences/$id'
      preLoaderRoute: typeof EditSentencesIdRouteImport
      parentRoute: typeof EditRoute
    }
    '/learn/$slug/': {
      id: '/learn/$slug/'
      path: '/learn/$slug'
      fullPath: '/learn/$slug/'
      preLoaderRoute: typeof LearnSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug/$lessonId': {
      id: '/learn/$slug/$lessonId'
      path: '/learn/$slug/$lessonId'
      fullPath: '/learn/$slug/$lessonId'
      preLoaderRoute: typeof LearnSlugLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DevRouteChildren {
  DevKnobsRoute: typeof DevKnobsRoute
  DevMascotsRoute: typeof DevMascotsRoute
  DevPlaygroundRoute: typeof DevPlaygroundRoute
  DevIndexRoute: typeof DevIndexRoute
  DevDemoIdRoute: typeof DevDemoIdRoute
}

const DevRouteChildren: DevRouteChildren = {
  DevKnobsRoute: DevKnobsRoute,
  DevMascotsRoute: DevMascotsRoute,
  DevPlaygroundRoute: DevPlaygroundRoute,
  DevIndexRoute: DevIndexRoute,
  DevDemoIdRoute: DevDemoIdRoute,
}

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren)

interface EditRouteChildren {
  EditContentRoute: typeof EditContentRoute
  EditCultureRoute: typeof EditCultureRoute
  EditCurriculumRoute: typeof EditCurriculumRoute
  EditGoldensRoute: typeof EditGoldensRoute
  EditGrammarRoute: typeof EditGrammarRoute
  EditRecorderRoute: typeof EditRecorderRoute
  EditReviewRoute: typeof EditReviewRoute
  EditStudioRoute: typeof EditStudioRoute
  EditWriteRoute: typeof EditWriteRoute
  EditIndexRoute: typeof EditIndexRoute
  EditExercisesIdRoute: typeof EditExercisesIdRoute
  EditExercisesNewRoute: typeof EditExercisesNewRoute
  EditLexemesIdRoute: typeof EditLexemesIdRoute
  EditSentencesIdRoute: typeof EditSentencesIdRoute
  EditSentencesIndexRoute: typeof EditSentencesIndexRoute
}

const EditRouteChildren: EditRouteChildren = {
  EditContentRoute: EditContentRoute,
  EditCultureRoute: EditCultureRoute,
  EditCurriculumRoute: EditCurriculumRoute,
  EditGoldensRoute: EditGoldensRoute,
  EditGrammarRoute: EditGrammarRoute,
  EditRecorderRoute: EditRecorderRoute,
  EditReviewRoute: EditReviewRoute,
  EditStudioRoute: EditStudioRoute,
  EditWriteRoute: EditWriteRoute,
  EditIndexRoute: EditIndexRoute,
  EditExercisesIdRoute: EditExercisesIdRoute,
  EditExercisesNewRoute: EditExercisesNewRoute,
  EditLexemesIdRoute: EditLexemesIdRoute,
  EditSentencesIdRoute: EditSentencesIdRoute,
  EditSentencesIndexRoute: EditSentencesIndexRoute,
}

const EditRouteWithChildren = EditRoute._addFileChildren(EditRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  DevRoute: DevRouteWithChildren,
  EditRoute: EditRouteWithChildren,
  GrammarRoute: GrammarRoute,
  LeaguesRoute: LeaguesRoute,
  LexiconRoute: LexiconRoute,
  LicencesRoute: LicencesRoute,
  MistakesRoute: MistakesRoute,
  PlusRoute: PlusRoute,
  PreviewRoute: PreviewRoute,
  PrivacyRoute: PrivacyRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  WelcomeRoute: WelcomeRoute,
  WithdrawalFormRoute: WithdrawalFormRoute,
  LegalCompanyRoute: LegalCompanyRoute,
  PrivacyProvidersRoute: PrivacyProvidersRoute,
  LearnSlugLessonIdRoute: LearnSlugLessonIdRoute,
  LearnSlugIndexRoute: LearnSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
